# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    wrapper.guzzle:
      class: AppBundle\Services\GuzzleWrapper

    api.haveibeenpwnd:
      class: AppBundle\Services\HaveIBeenPwnd
      arguments: ['%haveibeenpwnd_baseurl%', '%haveibeenpwnd_version%','%haveibeenpwnd_useragent%', '@wrapper.guzzle', '@doctrine.orm.default_entity_manager']